name: Gitea Runner On GitHub Actions
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 下载官方 act-runner 0.6.1
        run: |
          wget https://dl.gitea.com/act_runner/0.6.1/act_runner-0.6.1-linux-amd64
          chmod +x act_runner-0.6.1-linux-amd64
          sudo mv act_runner-0.6.1-linux-amd64 /usr/local/bin/act_runner

      - name: 非交互注册 Gitea Runner
        env:
          GITEA_URL: ${{ secrets.GITEA_URL }}
          GITEA_TOKEN: ${{ secrets.GITEA_RUNNER_TOKEN }}
        run: |
          act_runner register \
            --no-interactive \
            --instance "${GITEA_URL}" \
            --token "${GITEA_TOKEN}" \
            --labels linux-x64

      - name: 启动守护监听任务
        run: |
          act_runner daemon &
          sleep 300
          pkill act_runner
